hmcts/div-ccd-definitions

package.json
Only AAT runs the Integration Test that requires the -staging url.
For Demo and Prod it is best to use the actual prod slot app for callbacks.
```
[ ] Yes
[x] No
```
=> Remove -staging part from Demo and Prod

definitions/divorce/json/FixedLists.json
[DIV-4859 - Add Certificate of Entitlement Document Type Enum](https://tools.hmcts.net/jira/browse/DIV-4859)
Adds the required Document Type enum for Certificate of Entitlement.
```
[ ] Yes
[x] No
```
=> Add Certificate of Entitlement Doc Type

definitions/divorce/json/CaseEvent.json
[DIV-4538 Case Orchestration Callback Component for Generating Co-Respondent Answers PDF](https://tools.hmcts.net/jira/browse/DIV-4538)
[DIV-4397 Co-Respondent Answers Generator](https://tools.hmcts.net/jira/browse/DIV-4397)
Adds the Co-Respondent Answers Generator Callback Url to all Co-Resp Received Events. This is because they need an answers document generated after submitting their response in an Undefend Journey. (Defended calls co-respondent-answer-recevied instead of the generator).
This must not be merged before https://github.com/hmcts/div-case-orchestration-service/pull/262 is deployed to Production.
```
[ ] Yes
[x] No
```
=> Call the Co-Resp Answers Generator Callback When Co-Resp AoS Recevied

definitions/divorce/json/CaseRoles.json, definitions/divorce/json/CaseType.json, definitions/divorce/json/CaseTypeTab.json
OR operator does not work for tab show condition . Only AND is handled.
So, created a new set of fields in another tab with the same name and diff show condition.
D8ReasonForDivorceAdulteryWishToName & D8ReasonForDivorceAdulteryIsNamed fields are to be shown only in ReasonForDivorce tab.
Replacement for PR:  https://github.com/hmcts/div-ccd-definitions/pull/14
[ccd-config-base.xlsx](https://github.com/hmcts/div-ccd-definitions/files/3199405/ccd-config-base.xlsx)
**Tested with** 
PFE journey
https://www-ccd.aat.platform.hmcts.net/case/DIVORCE/DIVORCE/1553524994931028#coRespondent
Solicitor Adultery journey
https://www-ccd.aat.platform.hmcts.net/case/DIVORCE/DIVORCE/1558089647667325#facts
https://www-ccd.aat.platform.hmcts.net/case/DIVORCE/DIVORCE/1558015802390213#SolicitorCoRespondent
=> Div 3503 solicitior co resp tab missing

definitions/divorce/json/CaseTypeTab.json
Duplicate coresp tab because of smaller case on case tab id for one field
=> Case mistake on tab id 

definitions/divorce/json/FixedLists.json
DIV-4838
removed unwanted RespAgreeToCostsEnum options
```
[ ] Yes
[x] No
```
=> DIV-4838 - removed unwanted RespAgreeToCostsEnum options

definitions/divorce/json/AuthorisationCaseField.json
https://tools.hmcts.net/jira/browse/DIV-5001
Adding permission to view  DecreeNisiGranted, whoPaysCosts, typeCostsDecision, costsOrderAdditionalInfo for citizen and beta role. permission for CostsClaimGranted are already there
```
[ ] Yes
[ ] No
```
=> DIV-5001 addiitonal permissions for beta role and citizen

definitions/divorce/json/FixedLists.json
A line was missing from the config which is added here.
https://tools.hmcts.net/jira/browse/DIV-5035
=> DIV-5035 Add missing fixed-list value for DivorceCostsOptionDN

definitions/divorce/json/CaseEventToFields.json, definitions/divorce/json/CaseType.json, definitions/divorce/json/CaseTypeTab.json
Legacy and new config using two fields for same purpose - this removes using the field `D8ReasonForDivorceAdulteryIsNamed` from events but keeps it config for legacy compatibility.
We now use `D8ReasonForDivorceAdulteryWishToName` for all events involving adultery.
https://tools.hmcts.net/jira/browse/DIV-5068
=> DIV-5068 Amend sols journey to use D8ReasonForDivorceAdulteryWishToName

definitions/divorce/json/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/DIV-5099
PetitionerSolicitorToEffectService removed from solicitorCreate and solicitorUpdate events.
Request to remove PetitionerSolicitorToEffectService from SolicitorCreate and SolicitorUpdate events. 
This is causing issues because personal service is not yet supported. 
This feature will later be added in as part of the Personal Service journey - DIV-4912
AC:
During solicitorCreate and solicitorUpdate, solicitor is not asked if they wish to effect personal service to the respondent on the respondent details page
=> Div 5099 personal service

definitions/divorce/json/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/DIV-5099
PetitionerSolicitorToEffectService removed from solicitorCreate and solicitorUpdate events.
Request to remove PetitionerSolicitorToEffectService from SolicitorCreate and SolicitorUpdate events. 
This is causing issues because personal service is not yet supported. 
This feature will later be added in as part of the Personal Service journey - DIV-4912
AC:
During solicitorCreate and solicitorUpdate, solicitor is not asked if they wish to effect personal service to the respondent on the respondent details page
=> DIV-5099-Personal-Service

package.json
None, bugfix
The bulk config for AAT was being overriden because the env variable for the filename was the same for ITHC as AAT (copy-paste error). This meant the ITHC file was overriding the AAT one (with the wrong URLs)
```
[ ] Yes
[x] No
```
=> Fixed ITHC typo for bulk-scan scripts

definitions/divorce/json/AuthorisationCaseEvent.json, definitions/divorce/json/AuthorisationCaseState.json
[DIV-5556 - Solicitor can't view case](https://tools.hmcts.net/jira/browse/DIV-5556)
This adds READ permissions for Petitioner Solicitor users to view cases that are currently in the AOS flow
(AosAwaiting -> AosStarted -> AosComplete (or AosSubmittedAwaitingAnswer), that has been started by the Respondent.
Solicitor already had READ permission for AwaitingDecreeNisi and DNPronounced state, but was missing READ for AwaitingPronouncement and AwaitingConsideration (the states between these two).
```
[ ] Yes
[x] No
```
=> DIV-5556 Solicitor can't view case in certain states

definitions/divorce/json/CaseEvent.json
https://tools.hmcts.net/jira/browse/DIV-5672
(also see corresponding endpoint : https://github.com/hmcts/div-case-orchestration-service/pull/441)
Callback url to 'COS /aos-overdue' added for events: aosNotReceived and aosNotReceivedStarted
```
[x] Yes
[ ] No
```
=> callback url added for when aos overdue

definitions/divorce/json/AuthorisationCaseEvent.json
DIV-5708 DIV-5824 DIV-5813
This was a prod bugfix applied in DIV-5707 / https://github.com/hmcts/div-ccd-definitions/commit/d222c3cc37dee3f54fde8b21c3951cc6c7028707 as a bugfix but not replicated to master
We need to do this to bring the 2 branches in sync and remove `prod`
The other 2 changes in that commit appear to be already in master
```
[x] Yes
[ ] No
```
=> DIV-5708 DIV-5824 DIV-5813 sync prod with master

definitions/divorce/json/CaseTypeTab.json
Following testing, it was established that the UIOnly_RespWillDefendDivorce should not display in the AOS tab, and instead its value should be passed into RespWillDefendDivorce by a callback for all AOS Offline forms using it (DIV-5718)
```
[ ] Yes
[x] No
```
=> DIV-4803: Remove redundant AOS tab UIOnly_RespWillDefendDivorce field

charts/div-ccd-definitions/Chart.yaml, definitions/divorce/json/AuthorisationCaseEvent.json, definitions/divorce/json/AuthorisationCaseField.json, definitions/divorce/json/AuthorisationCaseState.json, definitions/divorce/json/CaseEvent.json, definitions/divorce/json/CaseField.json
Updated Divorce CCD spreadsheet according to RBS documentation for BSP Phase 2 and 2.1
https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1064666568#TechnicalprerequisitesandinformationforServiceon-boardingwithPhase2Bulkscanningforcasecreation.-2.1CCDConfiguration
=> BSP-115: added bulkScanCaseReference and events needed for BSP 2.1

definitions/divorce/json/CaseEventToFields.json, definitions/divorce/json/CaseField.json
Repo is not currently synced with the lastest config upload - changes weren't stored in github
Change FamilyMan reference validations to remove the restriction to 80k -99.9k digits
update page display order
```
[ ] Yes
[x] No
```
=> Update Json with lastest uploaded prod excel

definitions/divorce/json/CaseEventToFields.json
https://tools.hmcts.net/jira/browse/RPET-32
Removed the 'fieldshowcondition' on the 'issueFromSubmitted' event for the 'd8CaseReference' field. Was necessary so that it may added to the case data.
```
[ ] Yes
[x] No
```
=> fieldshowcondition removed so familyman displays again

definitions/divorce/json/FixedLists.json
https://tools.hmcts.net/jira/browse/RPET-150
Adding cheque payment option back. Labelled as 'cheque (DO NOT USE)' so that it is not used
```
[ ] Yes
[x] No
```
=> cheque payment option added back with DO NOT USE

definitions/divorce/json/AuthorisationCaseEvent.json
https://tools.hmcts.net/jira/browse/RPET-42
The authorisations for the following events: 'transfer between RDC' and 'transfer from CTSC to RDC' were modified to only be available to super users.
```
[ ] Yes
[x] No
```
=> transfer events only for super users

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-pcq-nonprod.json, definitions/divorce/json/CaseField/CaseField-pcq-nonprod.json, definitions/divorce/json/CaseTypeTab/CaseTypeTab-pcq-nonprod.json
https://tools.hmcts.net/jira/browse/PCQ-493
Update to correct spelling of respondent and co-respondent fields.
```
[ ] Yes
[x] No
```
=> PCQ-493: Corrected spelling in respondent field.

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json, definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-prod.json, definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json, test/unit/definitions/divorce/AuthorisationCaseField.test.js, test/unit/definitions/divorce/AuthorisationCaseState.test.js, test/unit/definitions/divorce/AuthorisationCaseType.test.js
https://tools.hmcts.net/jira/browse/DIV-6198
Currently, when trying to create a new case using a solicitor.
The workflow would fail if the case data contains the following fields:
* D8Cohort
* PreviousIssueDate
This is because in the definition file (i.e. div-ccd-definitions), solicitors do not have the necessary permissions to create a case with those fields.
**Action**
Adjusted authorisations to allow solicitors to create amended case.
```
[ ] Yes
[x] No
```
=> DIV-6420 (sub-task DIV-6198) field authorisations modified to enable solicitors create new amended cases

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-prod.json, definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-solicitorDn-nonprod.json, definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
https://tools.hmcts.net/jira/browse/DIV-6198
I previously added authorisations to allow the solicitor to run the event: amendPetitionForRefusalRejection
Those authorisations are actually not necessary. Putting it back the way it was before.
```
[ ] Yes
[x] No
```
=> DIV-6198: Previously added event authorisation removed

definitions/divorce/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DIV-6193
Currently, the 'amendPetition' event can only be called from the state 'AOSCompleted'.
A new pre-state condition has been added so that this event can be triggered from 'AwaitingAmendCase'.
```
[ ] Yes
[x] No
```
=> DIV-6193: Adding permissions to allow amendPetition event to be triggered from awaitingAmendCase

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-pcq-nonprod.json, definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-pet-amend-nonprod.json
https://tools.hmcts.net/jira/browse/PCQ-369
Add missing states for caseworker-divorce-pcqextractor role.
```
[ ] Yes
[x] No
```
=> PCQ-369: Add missing states for caseworker-divorce-pcqextractor role

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-deemed-and-dispensed-nonprod.json, definitions/divorce/json/CaseEventToFields/CaseEventToFields-deemed-and-dispensed-nonprod.json, definitions/divorce/json/CaseField/CaseField-deemed-and-dispensed-nonprod.json
https://tools.hmcts.net/jira/browse/DIV-6094
At the decree nisi stage the solicitor is usually presented with a page with a link to the respondent's answers.
Where the case has proceeded to decree nisi stage on the basis of deemed or dispensed, then the answers are not available.
Instead some explanatory text should be set (explaining why no answers are available).
```
[ ] Yes
[x] No
```
=> DIV-6094: When deemed or dispensed approved, display text, not respondent answers document

definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json
I have missed one AC:
```
AC2 General order check your answers
GIVEN a case is in any state
WHEN the caseworker-beta triggers the event 'createGeneralOrder'
AND completes the fields in the 'general order' page
AND clicks on continue
AND they are taken to the 'General order draft' page
AND they click on continue
THEN they are taken to the check your answers page
```
According to CCD documentation this should be enough:
https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=767557735#IntroductiontoCCDConfiguration-UserGuide-k)Summary'CheckYourAnswers'page
Story:
https://tools.hmcts.net/jira/browse/DIV-6142
=> DIV-6142: check your answer page for event createGeneralOrder

definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json
Callback:
```
/create-general-order/draft
```
must be added to page before. Otherwise the document will not be generated when user views this page and it's not working as expected. And this must be added to definition of the first field of that page (`"PageFieldDisplayOrder": 1`).
**Story:**
https://tools.hmcts.net/jira/browse/DIV-6142
=> DIV-6142: '/create-general-order/draft' should be added to page before the draft doc is displayed

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-pet-amend-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-pet-amend-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-prod.json, definitions/divorce/json/CaseEvent/CaseEvent.json, test/unit/definitions/divorce/AuthorisationCaseEvent.test.js, test/unit/definitions/divorce/CaseEventToFields.test.js
https://tools.hmcts.net/jira/browse/DIV-6479
As a caseworker
If a solicitor gets in touch with the courts saying that want to amend a case,
AND they accidentally trigger the event 'allow petitioner to amend' (which is not required for a solicitor case)
THEN the solicitor is still able to trigger the event 'Submit amended Petition' i.e. the case is not 'dead-ended'
```
[ ] Yes
[x] No
```
=> DIV-6479: Allow solicitor to amend from state 'AwaitingAmendCase'

definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json
GeneralOrderDraft should be READONLY, otherwise:
=> DIV-6142: GeneralOrderDraft on event page should be READONLY

definitions/divorce/json/CaseEventToFields/CaseEventToFields-deemed-and-dispensed-nonprod.json, definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json, definitions/divorce/json/CaseEventToFields/CaseEventToFields.json, test/unit/definitions/divorce/CaseEventToFields.test.js
`RetriesTimeoutURLMidEvent` should not be used at all.
This field is ignored by CCD.
https://github.com/hmcts/ccd-data-store-api/blob/97778561b9327f05eb16bd349b24d48c0ad6171a/src/main/java/uk/gov/hmcts/ccd/domain/service/callbacks/CallbackService.java#L46
=> DIV-6240: RetriesTimeoutURLMidEvent moved to the right definition

definitions/divorce/json/CaseEvent/CaseEvent-general-order-nonprod.json
We need to save data in ccd. So that `CallBackURLAboutToSubmitEvent` callback must be used since `CallBackURLSubmittedEvent` will not update case date with response from callback.
=> DIV-6142: use CallBackURLAboutToSubmitEvent instead of CallBackURLSubmittedEvent

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-deemed-and-dispensed-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-deemed-and-dispensed-nonprod.json
it's the same we have here:
https://github.com/hmcts/div-ccd-definitions/pull/487
But PR-487 is making weird things and I want to see if this can be built properly on different PR.
Story:
https://tools.hmcts.net/jira/browse/DIV-6509
Add with Permissions:
|CaseEvent|Admin|Beta|La|Sol|Super|Cit
-- |-- | --| -- |--|--|--
|aosNotReceivedFromServiceAppRejected| R | CRU | R | R | R | - 
|solAosNotReceivedFromServiceAppRejected| R | R | R | CRU | R | - 
|startAosFromServiceAppRejected| R | CRU | R | R | R | CRU 
|answerReceivedFromServiceAppRejected| R | CRU | R | R | R | R 
|coRespAnswerReceivedFromServiceAppRejected| R | CRU | R | R | R | R 
|IssueAOSOffline_Respondent_FromServiceAppRejected| R | CRU | R | R | R | R 
|IssueAOSOffline_CoRespondent_FromServiceAppRejected| R | CRU | R | R | R | R …
=> DIV-6509: Add ServiceApplicationNotApproved

test/unit/definitions/divorce/UserRoleStateAuth.test.js
it was taken from outdated PR:
https://github.com/hmcts/div-ccd-definitions/pull/441/files#diff-7642be724aa28dc92da242215df5b984R21
PR-441 was closed as we have already released that feature using different PRs.
=> DIV-6443: update list of excluded states

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-deemed-and-dispensed-nonprod.json
Trigger `Confirm service payment` event more than once requires more permissions. 
I don't know why, but when I remove `D` it doesn't work.
**Story:**
https://tools.hmcts.net/jira/browse/DIV-6595
=> DIV-6595: add more permissions to be able to trigger event more than once

definitions/divorce/json/CaseField/CaseField-deemed-and-dispensed-nonprod.json, definitions/divorce/json/ComplexTypes/ComplexTypes-deemed-and-dispensed-nonprod.json, definitions/divorce/json/FixedLists/FixedLists.json
https://tools.hmcts.net/jira/browse/DIV-6166
This change will change `ServiceApplicationPaymentTypeEnum` to `PaymentTypeEnum`.
This is so that two files under feature toggle can use the same information
This is needed to satisfy below.
AC4: Select payment type
GIVEN a case is in the state 'AwaitingGeneralReferralPayment'
WHEN a caseworker triggers the event 'General referral payment'
THEN General referral payment screen show
AND the caseworker is able to select which payment type has been used from a 'how will payment be made?' fixed list. This list includes 'Fee account';'Help with fees'; 'Cheque'; 'Telephone' (this requires a new fixed list in CCD for serviceApplicationPaymentType).
AC5: Selecting fee account from payment type
GIVEN a caseworker has triggered the event 'General referral …
=> Update FieldTypeParameter to make more generic

definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-referral-nonprod.json
https://tools.hmcts.net/jira/browse/DIV-6166
This hides a field that although has the COS implimentation to to display the Fee amount, is limited by the CCD config to output it on page load.
This will be addressed in a future ticket (https://tools.hmcts.net/jira/browse/RDM-10117), where they will simply undo the change i have made in this PR
=> DIV-6166: Hide Fee value field (waiting for: RDM-10117)

definitions/divorce/json/CaseTypeTab/CaseTypeTab-resp-journey-roles-and-permissions-nonprod.json, test/unit/utils/caseTabTypeHelper.js
All ACs implemented, except for "Service Application" tab (which needs a further decision).
```
[ ] Yes
[X] No
```
=> DIV-6710: Implementing tabs for resp-solicitor

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-share-a-case-nonprod.json, test/unit/definitions/divorce/UserRoleStateAuth.test.js
https://tools.hmcts.net/jira/browse/DIV-6637
When the `solicitorStatementOfTruthPaySubmit` event is triggered by the solicitor when they about to submit a case
`{
"ID": "solicitorStatementOfTruthPaySubmit",
"Name": "Case submission",
"Description": "Agree Statement of Truth, Pay & Submit",
"PreConditionState(s)": "SOTAgreementPayAndSubmitRequired",
"PostConditionState": "*",
"CallBackURLAboutToStartEvent": "${CCD_DEF_COS_URL}/petition-issue-fees",
"CallBackURLAboutToSubmitEvent": "${CCD_DEF_COS_URL}/process-pba-payment",
"CallBackURLSubmittedEvent": "${CCD_DEF_COS_URL}/allow-share-a-case",
}
`
There are about 3 possible states the case can end up depending on if it's a `FeeAccount`, `HWF` or some other forms of payment. At the time the case is being assigned in the …
=> DIV-6637 Allow a case with state - State Update

test/unit/definitions/divorce/CaseTypeTab.test.js
This adds a new tab visibility test capability and implements the ACs in the aforementioned stories as unit tests.
```
[ ] Yes
[X] No
```
=> DIV-6709 and DIV-6710: Implemented acceptance criteria as unit tests

definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-roles-and-permissions-nonprod.json
The FieldShowCondition of Respondent organisation policy fields was updated in https://github.com/hmcts/div-ccd-definitions/pull/682/files.
This was to not show those fields in the unlikely scenario where the user would do the following:
-  Click "Yes" to the question: Is the respondent represented by a solicitor?
- Click "Yes" to:  digital respondent case
- (They change their mind) and Click "No" to the question: Is the respondent represented by a solicitor?
- In this scenario, the respondent organisation field would still show on the screen (Unless they go back to set "Digital respondent case" to "No")
```
[ ] Yes
[x] No
```
=> Removing extra condition

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json, definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-prod.json, definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json, definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-prod.json, definitions/divorce/json/CaseEvent/CaseEvent.json
**Acceptance criteria**
1.   General Referral. The event 'General referral' can be triggered from the state 'AOSdrafted'. Note: Because 'General referral is available from any state, this will happen automatically.
2.     Caseworker-divorce-beta is given CRU access to the 'AosDrafted' state
3.     Serve by process server. The 'serveByProcessServer' pre-condition states extended to include 'AosDrafted'
4.     Confirm process server service. The 'confirmProcessServerService' event, pre-condition states extended to include 'AOSdrafted'
5.     A new Reissue event. The new 'Reissue' from the state 'AOS drafted'
```
[ ] Yes
[ ] No
```
=> DIV-6779: extend pre conditions for general referral / alt services

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-bailiff-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-bailiff-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-bailiff-prod.json, definitions/divorce/json/CaseEvent/CaseEvent.json
https://tools.hmcts.net/jira/browse/DIV-6778
Acceptance criteria
Draft AOS. The event 'solicitorDraftAOS' pre-state conditions to be extended to include 'AwaitingBailiffReferral' 'AwaitingBailiffService', 'IssuedToBailiff', (no change to post-state: event goes to 'solicitorDraftAOS') (DEV NOTE: Current "PostConditionState" for  "solicitorDraftAOS is "AosDrafted")
Update AOS. The event 'solicitorUpdateAOS' pre-state conditions are extended to include 'AwaitingBailiffReferral' 'AwaitingBailiffService', 'IssuedToBailiff'. (no change to post state i.e. goes to 'AOSdrafted')
Submit AOS. The event 'solicitorSubmitAOS' pre-state conditions to be extended to include 'AwaitingBailiffReferral' 'AwaitingBailiffService', 'IssuedToBailiff', (no change to post-state logic)
**Does this PR introduce a …
=> DIV-6778: Extend respondent solicitor AOS events pre-states to include Bailiff journey states

package.json
By mistake we used the same name for ITHC prod and non-prod so that `ccd-config-ithc.xlsx` file (nonprod) was generated successfully and then the same file was overwritten with prod-like content.
=> Generate ITHC prod-like xlsx properly

definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-prod.json, definitions/divorce/json/CaseEvent/CaseEvent.json
On prod for now `issueAosFromReissue.CallBackURLSubmittedEvent` stays unchanged.
Behind feature toggle it calls new endpoint.
Story:
https://tools.hmcts.net/jira/browse/DIV-6762
DO NOT MERGE until https://github.com/hmcts/div-case-orchestration-service/pull/1332 is merged.
=> DIV-6762: updated 'issueAosFromReissue.CallBackURLSubmittedEvent'

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-bailiff-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-bailiff-nonprod.json, definitions/divorce/json/CaseEventToFields/CaseEventToFields-bailiff-nonprod.json
https://tools.hmcts.net/jira/browse/DIV-6839
Acceptance criteria
```
Transfer from CTSC to RDC
GIVEN a case is in any of these states: AwaitingBailiffReferral;AwaitingBailifService;IssueToBailiff;AwaitingAOSBailiff;AwaitingService Consideration,AwaitingServicePayment,AwaitingGeneralApplicationPayment,AwaitingGeneralConsideration,GeneralConsiderationComplete;DNPronounced
THEN a caseworker can trigger the event 'Transfer from CTSC to RDC'
AND a screen appears where the user can select a value from the drop-down for D8DivorceUnit (see attached screenshots)
AND when the event is submitted state is changed to 'Issued'
```
```
[ ] Yes
[ ] No
```
=> DIV-6839 Transfer to CTSC from Service journey / Bailiff states

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-nonprod.json
https://tools.hmcts.net/jira/browse/DIV-6228
Needed a test event to move a case to one of the bailiff related states to enable cover Integration test for the bailiff feature for when respondent/co-respondent AoS responses come in.
Test event added in `-nonprod` feature file and should not make it to prod.
```
[ ] Yes
[x] No
```
=> DIV-6228: Citizen respondent-co-respondent can submit AOS response whilst bailiff application in progress

definitions/divorce/json/CaseEvent/CaseEvent-bailiff-or-resp-journey-nonprod.json, definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json, test/unit/utils/dataProvider.js
https://tools.hmcts.net/jira/browse/DIV-6846
Adds `Submitted;Issued;AwaitingDocuments` to pre condition states of `serviceApplicationReceived`. To be released with bailiff or resp-journey release, whichever comes first
```
[ ] Yes
[x] No
```
=> DIV-6846 - Ability to trigger 'Service application received' prior to issue

definitions/divorce/json/FixedLists/FixedLists-bailiff-nonprod.json
https://tools.hmcts.net/jira/browse/DIV-6806
Adds the following document types:
- Bailiff Certificate of Service
- Objection to Costs
```
[ ] Yes
[x] No
```
=> DIV-6806 - Add 'Bailiff Certificate of Service' and 'Objection to Costs' document types

test/data/case-creation-basic-data.json, test/data/case-creation-solicitor.json, test/functional/caseCreation_test.js
After making PetitionerOrganisationPolicy a mandatory field in the callback we must update test data.
Secret:
```
ccd-e2e-solicitor-email = divorce_as_petitioner_solicitor_02@mailinator.com
```
in preview and aat.
Story:
https://tools.hmcts.net/jira/browse/DIV-6847
=> DIV-6847: fixed functional tests

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-share-a-case-nonprod.json
Story:
https://tools.hmcts.net/jira/browse/DIV-6858
Business requirements: when case is submitted (states: solicitorAwaitingPaymentConfirmation and Submitted) CAA must not see it on list of unassigned cases in manage-org.
=> DIV-6858: no permissions for CCA role on solicitorAwaitingPaymentConfirmation and Submitted states

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState.json
https://tools.hmcts.net/jira/browse/RPET-991
PRs:
https://github.com/hmcts/cnp-flux-config/pull/9730
https://github.com/hmcts/div-case-orchestration-service/pull/1427
Story:
https://tools.hmcts.net/jira/browse/RPET-991
States (from story: https://tools.hmcts.net/jira/browse/RPET-979):
- SOTAgreementPayAndSubmitRequired
- AwaitingHWFDecision
- AwaitingService
- Submitted
- solicitorAwaitingPaymentConfirmation
- AwaitingPayment
- AwaitingDocuments
- Issued
In terms of `AwaitingHWFDecision` we already have it:
```
{
"LiveFrom": "01/01/2017",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingHWFDecision",
"UserRole": "caseworker-divorce-solicitor",
"CRUD": "RU"
},
```
Notes:
```
{
"LiveFrom": "12/05/2021",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingPayment",
"UserRole": …
```
=> RPET-991: Update DIV state permissions for CAA role

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
Story:
https://tools.hmcts.net/jira/browse/RPET-1007
The behaviour was defined in:
https://tools.hmcts.net/jira/browse/DIV-6713
But there is a number of cases where petitioner solicitor created a case before Share a Case was released and submitted it after Share a Case was released.
Because data model has changed they were recognised as pet solicitors who don't want to be digital and Share a Case call to ACA api was not executed so that they didn't get [PETSOLICITOR] case role, but they still had [CREATOR] case role and caseworker-divorce-solicitor idam role so it was invisible for them until event "solApplyForDA".
In DIV-6713 there are also other events only [PETSOLICITOR] can trigger:
```
solConfirmPersonalService
solicitorApplyForDN
solicitorUpdateDN
solicitorSOTDN
solApplyForDA …
```
=> RPET-1007: Adding CRU permissions to [CREATOR] for events that should be triggered by [PETSOLICITOR]

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json, definitions/divorce/json/CaseEvent/CaseEvent.json, definitions/divorce/json/CaseField/CaseField.json, definitions/divorce/json/CaseTypeTab/CaseTypeTab.json, definitions/divorce/json/ComplexTypes/ComplexTypes.json, package.json
https://tools.hmcts.net/jira/browse/RPET-966
For existing general email functionality added:
- clearing CCD fields used for general email when the event is invoked 
```
[ ] Yes
[x] No
```
=> RPET-966 persist general email
