definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/CaseTypeTab.json

DIV-4626
- Added DNApprovalField
- Added Outcome if DN section
```
[ ] Yes
[ x] No
```

DIV-4626 Add DNApprovalDate

---

definitions/divorce/json/AuthorisationCaseType.json

Add Legal advisor role
```
[ ] Yes
[ ] No
```

DIV-4626 Add Legal advisor role

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/CaseTypeTab.json

Add CostsClaimGranted field
```
[ ] Yes
[ ] No
```

DIV-4626 Add CostsClaimGranted field

---

definitions/bulk-action/json/AuthorisationCaseField.json
definitions/bulk-action/json/CaseField.json
definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/CaseTypeTab.json
definitions/bulk-action/json/SearchResultFields.json
definitions/bulk-action/json/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/DIV-4823
- Add history tab to bulk case 
- Add case state and Pronouncement date (hearingDate) on view list 
```
[ ] Yes
[x ] No
```

DIV-4834 added case history and bulk list view

---

definitions/divorce/json/CaseRoles.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/CaseTypeTab.json

D8ReasonForDivorceAdulteryIsNamed - is the field which is used in the whole solicitor journey

Div 3503 solicitior co resp tab missing

---

Jenkinsfile_CNP
README.md
package.json
sonar-project.properties
test/definitions/divorce/CaseEvent.test.js
yarn.lock

Initial Jenkinsfile to create a pipeline for building/testing the CCD config
```
[ ] Yes
[ ] No
```

DIV-4849 - initial Jenkinsfile

---

README.md
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/CaseTypeTab.json
definitions/divorce/json/FixedLists.json
definitions/divorce/json/UserProfile.json
package.json

https://tools.hmcts.net/jira/browse/DIV-4818
Adding second (optional) screen to Decree Nisi approval process
THIS PR CONTAINS ALL CHANGES CONTAINED IN #25
```
[ ] Yes
[X ] No
```

DIV-4818: Adding second (optional) screen to Decree Nisi approval process

---

Jenkinsfile_CNP
test/definitions/divorce/CaseEvent.test.js

Add artifacts to jenkins build, so that anyone can download them
```
[ ] Yes
[ ] No
```

DIV-4849 - Add artifacts to jenkins build, so that anyone can download them 

---

definitions/divorce/json/CaseType.json
definitions/divorce/json/FixedLists.json

Added cost order type in ccd for 
https://tools.hmcts.net/jira/browse/DIV-4831
```
[ ] Yes
[x] No
```

DIV-4831 added Costs Order type in fixedLists

---

definitions/divorce/json/CaseField.json

https://tools.hmcts.net/jira/browse/DIV-4979

Label change

---

definitions/divorce/json/FixedLists.json

https://tools.hmcts.net/jira/browse/DIV-4838

Remove "different amount" fields in the cost order section for DN

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/DIV-5002

Moving midevent callback to caseEventToFields

---

definitions/bulk-action/json/AuthorisationCaseField.json
definitions/bulk-action/json/CaseField.json
definitions/bulk-action/json/CaseType.json
definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json

[DIV-4827 - Caseworker Pronounce Bulk DN](https://tools.hmcts.net/jira/browse/DIV-4827)
The fields added in this PR are required for the above JIRA ticket.
CCD UI Views such as showing the data on the tab will be a separate story.
```
[ ] Yes
[x] No
```

DIV-4827 DN Pronouncement Required Fields

---

definitions/bulk-action/json/AuthorisationCaseEvent.json
definitions/bulk-action/json/AuthorisationCaseState.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/State.json

[DIV-4827](https://tools.hmcts.net/jira/browse/DIV-4827)
Required for DN Pronouncement.

Dn Pronouncement Event and Callback

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseType.json

Adding Read permission for LA on CourtName field
https://tools.hmcts.net/jira/browse/DIV-5001
```
[ ] Yes
[x] No
```

Add Read permission for LA on CourtName field

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseType.json

Allowing CW Beta Role to see `Make a decision`event in CCD web ui History tab   
https://tools.hmcts.net/jira/browse/DIV-5001
```
[ ] Yes
[x] No
```

DIV-5001 Make a decision, Read permission for beta role

---

definitions/divorce/json/CaseType.json
definitions/divorce/json/State.json

Added
"TitleDisplay": "${[CASE_REFERENCE]}: ${D8PetitionerLastName} vs ${D8RespondentLastName}"
to State tab
https://tools.hmcts.net/jira/browse/DIV-4793

Updated case title in CCD

---

definitions/divorce/json/CaseTypeTab.json

DIV-4630
fix incorrectly field ID (should be the ID instead of type)
```
[ ] Yes
[x] No
```

DIV-4630 - fix incorrectly field ID (should be the ID instead of type)

---

definitions/divorce/json/CaseEventToFields.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json

DIV-4300. 
Updated labels used to match respondent confidential feature and added bold

Div 4300 confidential co resp

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json

None
This was causing an issue when I upload the file to AAT but somehow it worked for Gavin and in Prod without it somehow..
```
[ ] Yes
[x] No
```

Removed unwanted spaces for co-respondent labels

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/UserProfile.json

Fixes a Prod issue / and several incidents regarding being able to view the Respondent details in CCD if the user is RDC role (courtadmin) 
INC0473535 & INC0473664

Added auth for RespondentContactDetailsConfidential to RDC court admin

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json

https://tools.hmcts.net/jira/browse/DIV-4958
Add DnOutcomeLaChecked field
```
[ ] Yes
[ ] No
```

DIV-4958 Add DnOutcomeLaChecked field

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseType.json

As consequence of recent changes we have received SN ticket(s) relating to RDC staff not being able to progress cases.
We did this as per agreed design, however it has interfered with their workflow too much so we are reverting the change. 
https://tools.hmcts.net/jira/browse/DIV-5096

DIV-5096 Re-add missing RDC permissions

---

definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/FixedLists.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/FixedLists.json

Simply reordering the items which appear in the Court drop down list.

Made Court List Alphabetical Order

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

[DIV-5088 - DN Pronounced Document Generator Callback](https://tools.hmcts.net/jira/browse/DIV-5088)
NOTE: DO NOT MERGE until https://github.com/hmcts/div-case-orchestration-service/pull/330 is merged.

Added callback to generate DN pronouncement documents

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json

DIV-4958
Added field to know if the case is processed for outcome of DN
```
[ ] Yes
[ ] No
```

DIV-4958 Set outcome of dn field

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseType.json

DIV-4630
So that they we can update the case with their email without changing state
```
[ ] Yes
[x] No
```

DIV-4630 - allow solicitor to use the linkRespondent event

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json

https://tools.hmcts.net/jira/browse/DIV-5121
added DecreeAbsoluteGrantedDate field and permissions

Added field and permissions

---

definitions/bulk-action/json/AuthorisationCaseState.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/State.json
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/State.json

[DIV-4947](https://tools.hmcts.net/jira/browse/DIV-4947)
Adds a DN Pronouncement event to be triggered by the Bulk Update which will move cases within that bulk case to DNPronounced.

Point Bulk Triggered Events to DNPronounced State

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseType.json

Citizens need to see DN Outcome Fields on the frontend.

Added citizen read permissions for DN Outcome fields

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json

Removed D8RespondentSolicitorDetails field.
It was unused and was causing an import error

Removed unused field causing import error

---

definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/State.json

None
Removed duplicate DNPronounced state causing upload error
```
[ ] Yes
[x] No
```

Removed duplicate DNPronounced state causing upload error

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

Move make decision event to Awaiting LA

---

definitions/divorce/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/DIV-5139
Added show condition for solicitor adultery field to co-respondent decision in cost order process

added condition to allow solicitor cases to include co-responded costorder

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

Adds missing notification callbacks for Updating case with Court Hearing details as well as for Pronouncement.

Add missing notification callbacks for DN Outcome

---

definitions/divorce/json/CaseField.json

[DIV-5097](https://tools.hmcts.net/jira/browse/DIV-5097)
Need a label change to match PO requirements.

DIV-5097: Change label for DNApproval date

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/DIV-5140
Added clean state event to remove state from case data.
This event currently is triggered in post event callback after decision is made and only available for LA 
This event is not visible in vent history 
```
[ ] Yes
[ ] No
```

DIV-5140 Clean state

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseEvent.json

Creating test event for moving cases to DN Pronounced.

Creating test event for moving cases to DN Pronounced.

---

definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/CaseTypeTab.json
definitions/bulk-action/json/ComplexTypes.json

Renaming label of a field.
Removing duplicate caseTypeTab mapping to Prono8uncementJudge caseField.
Reordered display of fields

Modify label on bulk case DnApprovalDate

---

package.json

DIV-5117 
To test on the ITHC env
```
[ ] Yes
[x] No
```

DIV-5117 - added ITHC env config scripts

---

definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json

changes for DIV-5199 and DIV-5197 to be merged into prod
https://tools.hmcts.net/jira/browse/DIV-5199
https://tools.hmcts.net/jira/browse/DIV-5197
Update regex of familyman reference to support ZZ cases	
Added solicitor permissions for DN states

DIV-5199 and DIV-5197

---

definitions/divorce/json/CaseEventToFields.json

DIV-4953
Show cost order only if petitioner claim cost
```
[ ] Yes
[ ] No
```

DIV-4953 Add conditional on cost decision

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json
package.json

aboutTo callback for da granted event
https://tools.hmcts.net/jira/browse/DIV-4938
```
[ ] Yes
[x] No
```

DIV-4938 callback for da granted event

---

definitions/divorce/json/CaseEvent.json

This endpoint will be responsible for a few tasks that need to be performed before this event can be raised.
**Please do not merge it before the COS related PR is merged to master and deployed to PROD.**

DIV-5108: Pointing to the new endpoint

---

definitions/divorce/json/CaseEvent.json

Please only merge this once the following is merged and deployed to prod:
https://github.com/hmcts/div-case-orchestration-service/pull/362

DIV-5024: Calling new callback endpoint when case is made eligible for DA

---

definitions/bulk-action/json/AuthorisationCaseEvent.json
definitions/bulk-action/json/AuthorisationCaseField.json
definitions/bulk-action/json/AuthorisationCaseState.json
definitions/bulk-action/json/AuthorisationCaseType.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseType.json

DIV-5210
- Added cancel schedule for listing event for super user to move the bulk case back.
- Added permission to super user on bulkcases
```
[ ] Yes
[ ] No
```

DIV-5210 Add listing cancel

---

definitions/divorce/json/CaseEvent.json

Reverts hmcts/div-ccd-definitions#115
I've merged too soon.

Revert "DIV-5024: Calling new callback endpoint when case is made eligible for DA"

---

definitions/divorce/json/CaseEvent.json

Reverts hmcts/div-ccd-definitions#117
I've merged too soon.

Revert "DIV-5108: Pointing to the new endpoint"

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/CaseTypeTab.json
test/definitions/divorce/CaseTypeTab.test.js

https://tools.hmcts.net/jira/browse/DIV-5211
Added DA tab to CCD and additional fields needed to map to this tab
Field to display are:
ApplyForDecreeAbsolute
DecreeAbsoluteGranted
DecreeAbsoluteGrantedDate
Changed DecreeAbsoluteGrantedDate field to DateTime type. Added sub task to take care of ensuring the time doesn't appear on the DA document: https://tools.hmcts.net/jira/browse/DIV-5214

DA CCD changes

---

definitions/divorce/json/AuthorisationCaseType.json
definitions/divorce/json/CaseType.json

DIV-4630 
So that only superuser have access, to hide this unreleased feature from prod
```
[ ] Yes
[x] No
```

DIV-4630 - Remove authorisation for Notice of Acting

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

This makes sure the petitioner is notified about the case eligibility.

DIV-5024: Configuring callback endpoint for MakeEligibleForDA event

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

DIV-5227
As a petitioner, I want to know when the LA or judge need more information about my case, so that I know I need to log in to my account to answer some questions in order to help the case progress
```
[ ] Yes
[x] No
```

DIV-5227 - added clarification callback to dnClarificationRequested

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

removing unused callback 
https://tools.hmcts.net/jira/browse/DIV-5254
```
[x] Yes
[ ] No
```

DIV-5254 Removed unused callback after event trigger 

---

definitions/divorce/json/CaseEvent.json

Updating callback url to call to `/da-about-to-be-granted` endpoint in COS
```
[ ] Yes
[x] No
```

update callback url for GrantDecreeAbsolute

---

definitions/divorce/json/CaseEvent.json

Reverts hmcts/div-ccd-definitions#136

Revert "update callback url for GrantDecreeAbsolute"

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/DIV-5062

DIV-5062: Creating new fields for storing DA-related dates

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

DIV-4420: minipetition draft endpoints added to prod

---

definitions/bulk-action/json/AuthorisationCaseEvent.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseType.json
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseType.json

Div 5235
Changes cherrypicking changes from prod to master
```
[ ] Yes
[ ] No
```

Div 5235 regenerate listing master

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json

Fixed the pipeline issue caused by merge conflict on this PR - https://github.com/hmcts/div-ccd-definitions/pull/132/files

Added back DA respondent date fields and auths

---

definitions/divorce/json/AuthorisationCaseField.json

[Solicitor DN submission not working on CCD](https://tools.hmcts.net/jira/browse/DIV-5468)
Solicitor's are unable to submit DN, this fixes that issue.

DIV-5468 Adding missing auth for Sol DN submission

---

definitions/bulk-action/json/CaseEvent.json
definitions/divorce/json/CaseEvent.json

Fix callbacks

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEventToFields.json

This is required as extension of live bugfix ticket:
[Solicitor DN submission not working on CCD](https://tools.hmcts.net/jira/browse/DIV-5468)

Adding missing field auth for solicitor submit

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/AuthorisationCaseType.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields.json

Resolves conflicts and ensures master has the fixes needed to work on Sprint tickets.

Merge in Prod bug fixes into master

---

definitions/divorce/json/AuthorisationCaseState.json

Removed solicitor duplicated state

---

definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseType.json
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

* Add remove remove from bulk case callback
DIV-5237
```
[ ] Yes
[ ] No
```

Add remove callback (#143)

---

definitions/divorce/json/CaseEvent.json

Development work adding a new callback got merged by accident. This removes it.

DIV-4945 Remove unused callback

---

Dockerfile
Jenkinsfile_CNP
README.md
test/functional/admin_test.js
test/functional/steps_file.js

DIV-4850 
* Removed hmcts docker references and use the base public docker image
* Also added the option not to create CCD via a `[NO-CCD]` tag in PR title (validated via #159)
* Added functional tests to upload the config files
```
[ ] Yes
[x] No
```

DIV-4850 - CCD instance cleanup

---

README.md
charts/div-ccd-definitions/values.preview.template.yaml

Added service token used by cms
```
[ ] Yes
[x ] No
```

Set cms service token

---

definitions/bulk-action/json/AuthorisationCaseEvent.json
definitions/bulk-action/json/AuthorisationCaseState.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseEventToFields.json
definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/State.json
package.json

DIV-5492 Add drop bulk case event

---

definitions/bulk-action/json/AuthorisationCaseEvent.json
definitions/bulk-action/json/AuthorisationCaseState.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseEventToFields.json
definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/State.json
package.json

DIV-5492
Add drop  case functionality
```
[ ] Yes
[ ] No
```

DIV-5492 drop bulk case prod

---

definitions/divorce/json/AuthorisationCaseType.json
definitions/divorce/json/CaseEvent.json
package.json

DIV-4630
The /aos-solicitor-nominated callback needs to be in the CallBackURLAboutToSubmitEvent
as it modifies the case data. Data changed will not take effect in CallBackURLSubmittedEvent
```
[ ] Yes
[x] No
```

[NO-CCD] DIV-4630 - enabled Notice of Acting and moved sol nomination callback

---

.gitignore
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

https://tools.hmcts.net/jira/browse/DIV-5471
Adding new event to issue AOS pack (offline) for Respondent
This should only be merged once https://github.com/hmcts/div-case-orchestration-service/pull/395 is merged.

Adding new event to issue AOS pack (offline) for Respondent

---

definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

This PR needs to have https://github.com/hmcts/div-case-orchestration-service/pull/398 merged before this should be merged!
[DIV-5540](https://tools.hmcts.net/jira/browse/DIV-5540)
And call to `COS/da-requested-respondent-notification` when case is progressed from `AwaitingDecreeAbsolute` to `DARequested`
```
[ ] Yes
[ ] No
```

add call to  endpoint.

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json

[DIV-5500](https://tools.hmcts.net/jira/browse/DIV-5500)
Give READ for RDC Caseworker on AwaitingReissue state
New CaseEvent to move AwaitingReissue state to Issued state
CaseEvent Update Permissions for RDC Caseworker for the above event.
```
[ ] Yes
[x] No
```

DIV 5500 Give RDC Caseworker AwaitingReissue permissions

---

definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/FixedLists.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/FixedLists.json

https://tools.hmcts.net/jira/browse/DIV-5592
New court id added to dropdown. Related COS PR coming soon.
```
[ ] Yes
[x] No
```

Added Nottingham Justice Centre

---

definitions/bulk-action/json/CaseType.json
definitions/bulk-action/json/FixedLists.json
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/FixedLists.json

Merge latest prod changes into master.
```
[ ] Yes
[x] No
```

[NO-CCD] DIV-5556, DIV 5500,  DIV-5592 Solicitor and permissions

---

definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseType.json

DIV-5205
Added permissions on drafted states (AOS and DN) for caseworker roles to be able to see the cases.
```
[ ] Yes
[ ] No
```

Added permissions on drafted states for caseworker roles

---

definitions/bulk-action/json/AuthorisationCaseEvent.json
definitions/bulk-action/json/CaseEvent.json
definitions/bulk-action/json/CaseEventToFields.json
definitions/bulk-action/json/CaseType.json

DIV-4974 
Promoting changes from  https://github.com/hmcts/div-ccd-definitions/pull/197 to prod
- Added event to edit listed bulk cases.
- About to submit callback to create Pronouncement Just list document.
- After submit callback to update each individual divorce cases
```
[ ] Yes
[ ] No
```

DIV-4974 add edit bulk case listed prod

---

charts/div-ccd-definitions/requirements.yaml
charts/div-ccd-definitions/values.preview.template.yaml

DIV-4872
To fix CCD AKS build issue
```
[ ] Yes
[x] No
```

Update to the latest Helm charts

---

charts/div-ccd-definitions/values.preview.template.yaml
definitions/divorce/json/CaseRoles.json
definitions/divorce/json/CaseType.json
definitions/divorce/json/UserProfile.json

Adds the missing roles tab as per discussion in COS PR https://github.com/hmcts/div-case-orchestration-service/pull/357

DIV-4945 Added missing Roles tab

---

definitions/divorce/json/AuthorisationCaseState.json

[Just adds Read perms for citizen on DNDrafted](https://tools.hmcts.net/jira/browse/DIV-5613)

Adding missing auth for DN Drafted state

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseType.json

https://tools.hmcts.net/jira/browse/DIV-5602
```
[ ] Yes
[x] No
```

 DIV-5602 DecreeAbsoluteApplicationDate  field for RPA

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/State.json

[DIV-5291](https://tools.hmcts.net/jira/browse/DIV-5291)
Add DAOverdue CaseEvent and CaseState.
```
[ ] Yes
[x] No
```

DIV-5290 Add DAOverdue state and CaseEvent

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseEventToFields.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json
definitions/divorce/json/FixedLists.json

DIV-5226
DIV-5265
Added clarification question on refusal journey
```
[ ] Yes
[ ] No
```

[NO-CCD]DIV-5226 Added clarification  pages

---

definitions/divorce/json/AuthorisationCaseState.json

DIV-5707
So that the the case doesn't disappear when they're in that state
```
[ ] Yes
[x] No
```

DIV-5707 - add solicitor read permission to AwaitingReissue

---

charts/div-ccd-definitions/requirements.yaml
definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseType.json

DIV-5707
* added missing permission for super user to update sol case. Super user should be able to CRU on case in SOTAgreementPayAndSubmitRequired. This change is already in master but needed in prod sooner
* Added read permission for solicitor when case is in AwaitingReissue - because solicitor lost access to case once the case has moved to this state
```
[ ] Yes
[x] No
```

DIV-5707 - prod permissions

---

definitions/divorce/json/FixedLists.json

Fixed list updated for AOS offline invitation letters

---

definitions/divorce/json/FixedLists.json

https://tools.hmcts.net/jira/browse/DIV-5710
Added Bury St Edmunds to RDC fixed list

DIV-5710 - add Bury St Edmunds to RDC fixed list

---

definitions/bulk-action/json/FixedLists.json
definitions/divorce/json/FixedLists.json

https://tools.hmcts.net/jira/browse/DIV-5757
```
[ ] Yes
[x] No
```

Add Birmingham DN court

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/DIV-5730
added recovery event suggested by CCD to restore missing documents
```
[ ] Yes
[ ] No
```

 DIV-5730 missing doc link fix

---

package.json

Merged PR pointing config by mistake, this reverts it.

fix config

---

package.json

To point at the new staging AKS
```
[ ] Yes
[x] No
```

[NO-CCD] Update package.json

---

definitions/divorce/json/CaseField.json

[Update petitioner solicitor labels](https://tools.hmcts.net/jira/browse/DIV-5835)

DIV-5835 Update labels for tabs/form to be more specific

---

definitions/bulk-action/json/CaseType.json
definitions/divorce/json/CaseType.json

Bumpup version

---

definitions/divorce/json/FixedLists.json

https://tools.hmcts.net/jira/browse/DIV-5780
```
[ ] Yes
[ x] No
```

DIV-5780: Adding missing document types for AOS offline

---

definitions/divorce/json/CaseField.json

https://tools.hmcts.net/jira/browse/DIV-5785
Changed email from East Midlands to CTSC email address as solicitor cases are no longer routed through EMDU

Change EastMidlandsDivorce@Justice.gov.uk to contactdivorce@justice.gov.uk

---

README.md
definitions/divorce/json/CaseEvent.json
package.json
test/unit/definitions/divorce/UserEventAuthorisation.test.js

[Allow co-respondent to respond when case in AosAwaitingSol](https://tools.hmcts.net/jira/browse/DIV-5836)

Allow CoRespondent to submit a AosAwaitingSol case

---

definitions/divorce/json/CaseEvent.json

This has to be merged after https://github.com/hmcts/div-case-orchestration-service/pull/537
Adapting CCD to use the updated URL for AOS pack offline.

DIV-5718: Change endpoint to a more RESTful name

---

README.md
package.json

[NOCCD] Update README.md with submodule and CCD PR instructions

---

definitions/divorce/json/AuthorisationCaseEvent.json

All AOS Offline events should be R only as agreed, before prod when they will be amended accordingly.
```
[ ] Yes
[x] No
```

Feature toggle - AOS Offline Received events

---

definitions/divorce/json/SearchInputFields.json
definitions/divorce/json/WorkBasketInputFields.json

https://tools.hmcts.net/jira/browse/DIV-5890
added search criteria and filters for digital DN and DA journey

added search criteria and filters for digital DN and DA journey

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseType.json

Added CRU permission for Superuser so they can clean the state from the data body
```
[ ] Yes
[ ] No
```

Add SU permission on state field

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/DIV-5940
Added Delete permission for super user to delete a case note

DIV-5940 - Allow super user to delete a note

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField.json

Caseworkers have to be able to clean a case's state.
This is going to be called internally after a dynamic state is set by a callback.
```
[ ] Yes
[ x ] No
```

DIV-5718: Give caseworkers ability to clean a case's state

---

definitions/divorce/json/CaseEvent.json

DIV-5234 
Added callback for clarification submitted event
```
[ ] Yes
[ ] No
```

Div-5234 clarification email

---

definitions/divorce/json/AuthorisationCaseEvent.json

Fix dn clarification sol

---

definitions/divorce/json/CaseField.json

Update additional info label
```
[ ] Yes
[ ] No
```

[NO-CCD]Update additional info label

---

definitions/divorce/json/WorkBasketResultFields.json

https://tools.hmcts.net/jira/browse/DIV-5911
Added case list view ordering by last modified. 
https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1126761193&__ncforminfo=QUmukoaD-f_AEZ1BXJLdLkFX0VYbwaJUtb-7pu_qHqVA0XTWlqdOLIC-4i2SEei4_SxwyAYDFHaiAqw7_E_f9RJ7BNZ1MIB0

Added ordering by Last Modified Ascending

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json
definitions/divorce/json/UserProfile.json

https://tools.hmcts.net/jira/browse/BSP-108
New field added: D8LegalProceedingsDetailsCaseNumber (used in the D8 form)
```
[ ] Yes
[x] No
```

new field D8LegalProceedingsDetailsCaseNumber added

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/BSP-120
Created new field for 'RespStatementofTruthSignedDate'
Gave Read permission for Case Worker Beta, Court Admin & Legal Advisor

BSP-120: Added new field for RespStatementofTruthSignedDate

---

definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseField.json
definitions/divorce/json/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/BSP-102
```
[ ] Yes
[x] No
```

BSP-102 CCD fields

---

definitions/divorce/json/CaseField.json
definitions/divorce/json/FixedLists.json

This is only for the field names. The permissions for these fields will be configured once we know the right user roles to use.
```
[ ] Yes
[ x ] No
```

BSP-110: Creating fields for section 11 of the D8 form

---

definitions/divorce/json/CaseEvent.json

https://tools.hmcts.net/jira/browse/RPET-31
Changed callback in Confirm Service of sol personal journey.
```
[ ] Yes
[ x] No
```

changed callback to CallBackURLSubmittedEvent for sol personal service journ

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/RPET-53

RPET-53: Modifications in 'Transfer from CTSC to RDC' events permissions

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/AuthorisationCaseState.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields.json
definitions/divorce/json/CaseField.json
test/unit/definitions/divorce/UserRoleStateAuth.test.js

Adequating CCD definitions to work with BSP integration.
```
[ ] Yes
[ x ] No
```

Adding fields and permissions to make integration with BSP work

---

definitions/divorce/json/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields.json
test/unit/definitions/divorce/CaseTypeTab.test.js

https://tools.hmcts.net/jira/browse/WLA-169
Solicitor - Set language preference flag to bilingual
```
[ ] Yes
[x ] No
```

 WLA-169: Solicitor - Set language preference flag to bilingual

---

charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/requirements.yaml
definitions/divorce/json/AuthorisationCaseEvent.json

https://tools.hmcts.net/jira/browse/RPET-166
Turning on the feature of a petitioner's solicitor applying for Decree absolute.
```
[ ] Yes
[x] No
```

turning on pet solicitor applies for DA

---

definitions/divorce/json/AuthorisationCaseEvent.json

Reverts hmcts/div-ccd-definitions#346

Revert "transfer events only for super users"

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-prod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json

https://tools.hmcts.net/jira/browse/DIV-6360
The following fields
```
EnterAOSOffline_Respondent_fromAosAwaiting
EnterAOSOffline_Respondent_fromAosStarted
EnterAOSOffline_Respondent_fromAosOverdue
EnterAOSOffline_CoRespondent
```
Are set to ```CRU``` in Non-prod and ```R``` in Prod.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[X] No
```

Set events to be live on AAT

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RPET-242

Remove deprecated method installCharts

---

definitions/divorce/json/CaseField/CaseField-nonprod.json

Just a few extra fixes.
```
[ ] Yes
[ x ] No
```

DIV-6350: Extra fixes

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
definitions/divorce/json/CaseEvent.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-nonprod.json

Temporary (feature-toggled) event to allow us to test our stories.
```
[ ] Yes
[ ] No
```

DIV-6392: Create a temporary event to edit derived addresses

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields-nonprod.json

Adding the bulk listing case id to the temporary event so that it's easier to simulate the actions of the bulk case type.
```
[ ] Yes
[ x ] No
```

Adding bulk listing case id to test event

---

definitions/divorce/json/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/RPET-209
```
[ ] Yes
[x] No
```

RPET-209-2-year-consent-journey

---

Jenkinsfile_CNP
charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/requirements.yaml
charts/div-ccd-definitions/values.preview.template.yaml

Update CCD image to version 4.3.2 from 3.3.5 to fix builds on PR.
https://tools.hmcts.net/jira/browse/DIV-6423

DIV-6423: update config

---

Jenkinsfile_CNP
charts/div-ccd-definitions/values.aat.template.yaml
test/functional/steps_file.js

New env var for aat env to get to CCD_ADMIN_URL

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-prod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-solicitorDn-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-solicitorDn-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6198
Div-6198: Update authorisation for event amendPetitionForRefusalRejection to allow solicitor to trigger it.
This is required for the solicitor to be able to amend a case which has been refused for DN.
```
[ ] Yes
[x] No
```

Div-6198: Update authorisation for event amendPetitionForRefusalRejection

---

definitions/divorce/json/CaseEvent/CaseEvent-pet-amend-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-prod.json
definitions/divorce/json/CaseEvent/CaseEvent.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-nonprod.json
definitions/divorce/json/State/State-pet-amend-nonprod.json
definitions/divorce/json/State/State.json
package.json
test/unit/definitions/divorce/AuthorisationCaseEvent.test.js
test/unit/definitions/divorce/AuthorisationCaseField.test.js
test/unit/definitions/divorce/AuthorisationCaseState.test.js
test/unit/definitions/divorce/AuthorisationCaseType.test.js
test/unit/definitions/divorce/UserRoleStateAuth.test.js
test/unit/utils/utils.js
yarn.lock

DIV-6212: Adding dueDate to Temporary superuser's test event

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-pet-amend-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-pet-amend-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent.json
test/unit/definitions/divorce/UserRoleStateAuth.test.js

Fixing prod configuration

---

definitions/divorce/json/CaseEvent/CaseEvent-pet-amend-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6461
Removing certain pre-states to fix issues found in DIV-6193
```
[ ] Yes
[x] No
```

DIV-6461: Removing the specified pre-states from event definition

---

definitions/divorce/json/FixedLists/FixedLists.json

Story:
https://tools.hmcts.net/jira/browse/DIV-6237
One more d8 document type in fixed list.

DIV-6237: new type of d8 generated documents - dispenseWithServiceGranted

---

definitions/divorce/json/FixedLists/FixedLists.json

One more document type.
https://tools.hmcts.net/jira/browse/DIV-6238

DIV-6238: added d8 doc type: deemedAsServedGranted

---

definitions/divorce/json/CaseEvent/CaseEvent.json
package.json
test/unit/definitions/divorce/AuthorisationCaseEvent.test.js
yarn.lock

DIV-6470: Removing unwanted states from event

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-deemed-and-dispensed-nonprod.json
definitions/divorce/json/State/State-deemed-and-dispensed-nonprod.json

`AwaitingDecreeNisi` state has permissions:
```
{
"LiveFrom": "09/11/2018",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingDecreeNisi",
"UserRole": "caseworker-divorce-courtadmin_beta",
"CRUD": "CRU"
},
{
"LiveFrom": "09/11/2018",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingDecreeNisi",
"UserRole": "citizen",
"CRUD": "CRU"
},
{
"LiveFrom": "01/01/2017",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingDecreeNisi",
"UserRole": "caseworker-divorce-systemupdate",
"CRUD": "CRU"
},
{
"LiveFrom": "01/01/2017",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingDecreeNisi",
"UserRole": "caseworker-divorce-courtadmin",
"CRUD": "R"
},
{
"LiveFrom": "01/01/2017",
"CaseTypeID": "DIVORCE",
"CaseStateID": "AwaitingDecreeNisi",
"UserRole": "caseworker-divorce-bulkscan",
"CRUD": "RU"
},
{ …
```

DIV-5411: replace state AwaitingDNApplication with AwaitingDecreeNisi

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-deemed-and-dispensed-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-deemed-and-dispensed-nonprod.json

DIV-6213-Update-precondition-to-AwaitingServicePayment

---

package.json
yarn.lock

It's a vulnerability issue:
https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_DIV%2Fdiv-ccd-definitions/detail/master/89/pipeline

Upgrade serialize-javascript nodejs package to version 4.0.0

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-general-order-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-general-order-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-general-order-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json
definitions/divorce/json/CaseField/CaseField-general-order-nonprod.json
definitions/divorce/json/FixedLists/FixedLists-general-order-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6141
As a caseworker
I need to be able to create a general order for a variety of scenarios e.g. to update parties about a decision the courts have made around a general application (such as an application to search government databases for respondent's address).
```
[ ] Yes
[x] No
```

DIV-6141: Create general order event (first page)

---

definitions/divorce/json/FixedLists/FixedLists.json

DIV-6480: Adding new doctype

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-general-order-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-general-order-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json
definitions/divorce/json/CaseField/CaseField-general-order-nonprod.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab-general-order-nonprod.json

Callback for event + field (collection of DivorceDocument) to store generated general orders.
Callback for event's page + temp field (type DivorceDocument) to store draft of general order.
#Story:
https://tools.hmcts.net/jira/browse/DIV-6142

DIV-6142: general order draft and final

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-general-email-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-general-email-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-general-email-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-email-nonprod.json
definitions/divorce/json/CaseField/CaseField-general-email-nonprod.json
definitions/divorce/json/FixedLists/FixedLists-general-email-nonprod.json
package.json
test/unit/definitions/divorce/CaseEventToFields.test.js
yarn.lock

Story:
https://tools.hmcts.net/jira/browse/DIV-6190

DIV-6190: create general email

---

definitions/divorce/json/CaseEvent/CaseEvent-general-order-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-order-nonprod.json

Check your answer page should be displayed.

DIV-6142: add 'Check your answer page' for event createGeneralOrder

---

test/unit/definitions/divorce/AuthorisationCaseEvent.test.js
test/unit/definitions/divorce/AuthorisationCaseField.test.js
test/unit/definitions/divorce/AuthorisationCaseState.test.js
test/unit/utils/assertBuilders.js

Just to make it easier to spot any issue before importing xlsx to an instance of CCD.

Unit test if fields and events used to grant permissions exist

---

definitions/divorce/json/FixedLists/FixedLists-general-email-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6190

DIV-6190: add 'DisplayOrder' to 'GeneralEmailPartiesEnum'

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/divorce/json/CaseEvent/CaseEvent.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields.json
definitions/divorce/json/CaseField/CaseField.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab.json
definitions/divorce/json/ComplexTypes/ComplexTypes.json
definitions/divorce/json/FixedLists/FixedLists.json
test/unit/definitions/divorce/CaseTypeTab.test.js

https://tools.hmcts.net/jira/browse/RPET-192
```
[ ] Yes
[x] No
```

RPET-192-Confidential-documents tab

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-deemed-and-dispensed-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-deemed-and-dispensed-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6531
Just adding one of the events to be added in https://tools.hmcts.net/jira/browse/DIV-6509, so that https://tools.hmcts.net/jira/browse/DIV-6531 is not blocked by the other story.
```
[ ] Yes
[x] No
```

Div 6531 allow aos events from service application not approved

---

definitions/divorce/json/CaseField/CaseField-general-order-nonprod.json
definitions/divorce/json/ComplexTypes/ComplexTypes-general-order-nonprod.json
definitions/divorce/json/FixedLists/FixedLists-general-email-nonprod.json
definitions/divorce/json/FixedLists/FixedLists-general-order-nonprod.json

DIV-6496: Making enum name more generic and reusable

---

charts/div-ccd-definitions/values.preview.template.yaml

fix ccd definitions key-vault access

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-deemed-and-dispensed-nonprod.json
definitions/divorce/json/CaseField/CaseField-deemed-and-dispensed-nonprod.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab-deemed-and-dispensed-nonprod.json
definitions/divorce/json/ComplexTypes/ComplexTypes-deemed-and-dispensed-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6504

DIV-6504: added complex type DivorceServiceApplication and collection of it

---

definitions/divorce/json/FixedLists/FixedLists-bailiff-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6233
- Adding Bailiff to Service Application Received Screen
- NOTE: The Fixed List "ServiceApplicationPaymentTypeEnum" is behind a deemed&dispensed toggle
```
[ ] Yes
[x] No
```

DIV-6233: Bailiff service application received

---

definitions/divorce/json/CaseEvent/CaseEvent-general-referral-nonprod.json

This PR can be merged after that one:
https://github.com/hmcts/div-ccd-definitions/pull/517
+ when COS is updated to expose the endpoint.
Story:
https://tools.hmcts.net/jira/browse/DIV-6187

DIV-6187: callback to set GeneralReferralDecisionDate field

---

definitions/divorce/json/CaseTypeTab/CaseTypeTab-general-referral-nonprod.json

Added one more field to tab.
Story:
https://tools.hmcts.net/jira/browse/DIV-6168

DIV-6168: added 'AlternativeServiceMedium' to tab: 'generalReferral'

---

definitions/divorce/json/CaseField/CaseField-deemed-and-dispensed-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6607
Changing the label for service application collection from "Service applications" to "Previous service applications"
```
[ ] Yes
[x] No
```

DIV-6607: Updating Service application collection label name

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-served-by-alternative-method-nonprod.json
definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-served-by-alternative-method-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-served-by-alternative-method-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-general-referral-nonprod.json
definitions/divorce/json/State/State-served-by-alternative-method-nonprod.json
test/unit/definitions/divorce/AuthorisationCaseEvent.test.js
test/unit/definitions/divorce/AuthorisationCaseState.test.js
test/unit/definitions/divorce/CaseEvent.test.js
test/unit/definitions/divorce/UserRoleStateAuth.test.js

https://tools.hmcts.net/jira/browse/DIV-6170

DIV-6170: Add served by alternative method events

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-served-by-alternative-method-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-served-by-alternative-method-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6523

DIV-6523: confirmAlternativeService event

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-alt-service-process-server-nonprod.json
definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-alt-service-process-server-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-alt-service-process-server-nonprod.json
definitions/divorce/json/State/State-alt-service-process-server-nonprod.json
test/unit/definitions/divorce/AuthorisationCaseEvent.test.js
test/unit/definitions/divorce/AuthorisationCaseState.test.js

https://tools.hmcts.net/jira/browse/DIV-6175
New PR made due to change in ACs.
Add a state and event

DIV:6175 Add serve by process server event and awaiting process server service state

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-alt-service-process-server-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-alt-service-process-server-nonprod.json

DIV-6178: Adding new event to move case to AwaitingDecreeNisi state.

---

definitions/divorce/json/CaseEvent/CaseEvent-alt-service-process-server-nonprod.json

New endpoint for event `aosNotReceivedForProcessServer`.
**Story**
https://tools.hmcts.net/jira/browse/DIV-6522

DIV-6522: added 'submitted' callback endpoint for event 'aosNotReceivedForProcessServer'

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-alt-service-process-server-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-alt-service-process-server-nonprod.json
definitions/divorce/json/State/State-alt-service-process-server-nonprod.json

This PR is to replace:
https://github.com/hmcts/div-ccd-definitions/pull/542
as it was easier to start from the scratch than resolve all conflicts. 
I have sorted it out and applied what was done in PR-542.
Story:
https://tools.hmcts.net/jira/browse/DIV-6176

DIV-6176: Confirm process server

---

definitions/divorce/json/CaseEvent/CaseEvent-alt-service-process-server-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6176
Due to update of ACs, the NAME of the ID "confirmProcessServerService" should be updated to "Confirm process server"

DIV-6176-Rename-confirmProcessServerService

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json

This event will be used to set-up the integration test data using a field citizens have no access to writing.
```
[ ] Yes
[X] No
```

DIV-6178: Extending test event to be used by caseworker-beta

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json

This is for making the integration tests viable and clean.
```
[ ] Yes
[X] No
```

DIV-6178: Allowing caseworker to trigger test event

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-alternative-service-nonprod.json
definitions/divorce/json/CaseField/CaseField-alternative-service-nonprod.json
test/unit/definitions/divorce/AuthorisationCaseField.test.js

https://tools.hmcts.net/jira/browse/DIV-6642
New field (flag) for when "Confirm alternative service" is triggered.
```
[ ] Yes
[x] No
```

DIV-6642: New field servedByAlternativeMethod

---

definitions/divorce/json/CaseEvent/CaseEvent-alternative-service-nonprod.json

Story:
https://tools.hmcts.net/jira/browse/DIV-6644

DIV-6644: CallBackURLSubmittedEvent added to confirmAlternativeService event

---

package.json

fix for  https://www.npmjs.com/advisories/1589   that breaks the builds due to audit issue
```
yarn audit v1.22.10
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ini                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >1.3.6                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ codeceptjs                                                   │ …
```

fix for https://www.npmjs.com/advisories/1589

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-amend-court-orders.json
definitions/divorce/json/CaseEvent/CaseEvent-amend-court-orders.json

Story:
https://tools.hmcts.net/jira/browse/DIV-6730

DIV-6370: added updateCourtOrderDocuments event 

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-alternative-service-nonprod.json
definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-alt-service-process-server-nonprod.json
definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-alternative-service-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-alternative-service-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-deemed-and-dispensed-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-prod.json
definitions/divorce/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/DIV-6653
Allow StartAOS and SubmitAOS from the states: 
- AwaitingAlternativeService
- AwaitingProcessServerService
- AwaitingDWPResponse
```
[ ] Yes
[x] No
```

DIV-6653: Allow StartAOS and SubmitAOS from new states

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-deemed-and-dispensed-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6699

DIV-6699: Fix for no field found error

---

definitions/divorce/json/CaseEvent/CaseEvent.json

[RPET-567](https://tools.hmcts.net/jira/browse/RPET-567)
Separate solicitor confirm service into its own call

RPET-567: move solicitor confirm service into own call

---

definitions/divorce/json/CaseEvent/CaseEvent.json

Reverts hmcts/div-ccd-definitions#597

Revert "RPET-567: move solicitor confirm service into own call"

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields.json
definitions/divorce/json/CaseField/CaseField.json

https://tools.hmcts.net/jira/browse/DIV-6699
Fix for DIV-6094
```
[ ] Yes
[x] No
```

Fix for div-6094

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields-deemed-and-dispensed-nonprod.json

Quick fix DIV-6699

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState.json
definitions/divorce/json/AuthorisationCaseType/AuthorisationCaseType.json

https://tools.hmcts.net/jira/browse/RPET-710
Add authorisation roles for divorce notice of acting case type
part of INC5143686

RPET-710: Add auth roles for notice of acting

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-share-a-case-nonprod.json
test/unit/definitions/divorce/AuthorisationCaseEvent.test.js
test/unit/definitions/divorce/AuthorisationCaseState.test.js
test/unit/definitions/divorce/UserRoleStateAuth.test.js

Story:
https://tools.hmcts.net/jira/browse/DIV-6637
We need to grant caa user permission for a state.

DIV-6637: CRU for caa role on state 'SOTAgreementPayAndSubmitRequired'

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields-alt-service-process-server-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-alternative-service-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6746
Reorders labels
```
[ ] Yes
[x] No
```

DIV-6746: Placing label in proper position

---

definitions/divorce/json/CaseEvent/CaseEvent-share-a-case-nonprod.json

Adding the callback where Share a Case magic happens.

DIV-6637: add post-commit callback to 'solicitorStatementOfTruthPaySubmit'

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-general-referral-nonprod.json

Story:
https://tools.hmcts.net/jira/browse/DIV-6788
caserworker beta should has only R for generalConsideration event.

DIV-6788: beta role has R on event generalConsideration

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json

removed sol auths for add note event and notes field

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState.json

For Super user and caseworkers
```
[ ] Yes
[ ] No
```

RPET-743: Remove permission from AmendPetition

---

definitions/divorce/json/FixedLists/FixedLists.json

https://tools.hmcts.net/jira/browse/RPET-624
This PR is for removing an option from the list of payment methods that is displayed and causing confusion on the solicitor journey.
```
[ ] Yes
[X] No
```

RPET-624 Remove payment option CHEQUE from solicitor journey

---

definitions/divorce/json/CaseTypeTab/CaseTypeTab-resp-journey-roles-and-permissions-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6753
Adding Respondent solicitor's firm to tab
```
[ ] Yes
[x] No
```

DIV-6753: Adding Respondent organisation policy to tab

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState.json

So they can see the drop down box
```
[ ] Yes
[ ] No
```

RPET-743: Add CRU permission for AmendPetition State

---

definitions/divorce/json/CaseTypeTab/CaseTypeTab-resp-journey-roles-and-permissions-nonprod.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab.json
test/unit/definitions/divorce/CaseTypeTab.test.js

This guarantees order is kept after release.
```
[ ] Yes
[X] No
```

DIV-6749: Creating space for feature-toggled fields.

---

definitions/divorce/json/CaseTypeTab/CaseTypeTab-pet-sol-selects-own-org-nonprod.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab.json

https://tools.hmcts.net/jira/browse/DIV-6749
Re-ordering field in tab
```
[ ] Yes
[x] No
```

DIV-6749: Tab re-ordering

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-roles-and-permissions-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6754
Quick fix
```
[ ] Yes
[x] No
```

DIV-6574: Update of 'FieldShowCondition' for field 'RespondentOrganisationPolicy' on event 'solicitorUpdate'

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-roles-and-permissions-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6713
Change of AC requires a non prod CRU for UpdateLanguage:
```
{
"LiveFrom": "02/02/2021",
"CaseTypeID": "DIVORCE",
"CaseEventID": "UpdateLanguage",
"UserRole": "caseworker-divorce-solicitor",
"CRUD": "CRU"
},
```

DIV-6713-UpdateLanguage from R to CRU on sol role for non prod

---

charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/requirements.yaml

1. Copy over the `dependencies` definition in the `requirements.yaml` file into the `Charts.yaml`  file
2. update  `version: ~1.10.0` to `version: ~2.0.1` , in the `Charts.yaml` file
3. delete the `requirements.yaml` file
4. Change `apiVersion: v1` to `apiVersion: v2`  in the `Charts.yaml`  file
5. Bump `version: 1.0.2`  to `version: 2.0.0` in the `Charts.yaml`

Update apiVersion to v2

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-roles-and-permissions-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-resp-journey-roles-and-permissions-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-roles-and-permissions-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-roles-and-permissions-nonprod.json
definitions/divorce/json/CaseField/CaseField-resp-journey-roles-and-permissions-nonprod.json
test/unit/utils/dataProvider.js

https://tools.hmcts.net/jira/browse/DIV-6724
Adding page to update respondent solicitor contact details page
```
[ ] Yes
[x] No
```

DIV-6724: Adding page to update respondent solicitor contact details page

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-share-a-case-nonprod.json
test/unit/utils/dataProvider.js

It looks like we need those permissions. If they are removed assign access to case call is failing.

DIV-6710, DIV-6713: don't remove these PERMISSIONS

---

definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-roles-and-permissions-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-roles-and-permissions-prod.json
definitions/divorce/json/CaseEvent/CaseEvent.json
test/unit/utils/dataProvider.js

This pre-state should be added for RRJ release, not in DnD.

DIV-6776: don't release in DnD, this should be released with RRJ

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-roles-and-permissions-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6723
Made petitioner solicitor name a mandatory field
https://tools.hmcts.net/jira/browse/DIV-6723?focusedCommentId=948960&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-948960
```
[ ] Yes
[x] No
```

DIV-6723: Make petitioner solicitor name mandatory

---

charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/values.preview.template.yaml
config/default.yaml
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-roles-and-permissions-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6723
Minor update to handle duplicate page titles showing
```
[ ] Yes
[x] No
```

DIV-6723: Petitioner solicitor is able to update email, telephone and address

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-prod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json

**JIRA link** 
https://tools.hmcts.net/jira/browse/DIV-6713

DIV-6713: AC24 applied after DnD release

---

definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6765
Correct content to match desired:
Delivered
Desired: (Note there is an error below where the "O" in "AOS" should not be capitalised)
```
[ ] Yes
[ ] No
```

DIV-6765-Fix-content-Draft-Aos-Resp-Sol

---

definitions/divorce/json/CaseField/CaseField-resp-journey-nonprod.json

DIV-6765: Update label

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-prod.json

https://tools.hmcts.net/jira/browse/DIV-6713?focusedCommentId=942496&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-942496
Update permissions
```
[ ] Yes
[ ] No
```

AC22: Update PETSOL to be CRU on NonProd

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-resp-journey-prod.json

https://tools.hmcts.net/jira/browse/RPET-771
```
[ ] Yes
[x] No
```

RPET-771: Change cost claim form to optional.

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-resp-journey-nonprod.json

For some reason, this doesn't work with CRU only.
I'm not very sure that we should get this merged. I've posted a question on the ccd-questions group. Let's see what they say.
```
[ ] Yes
[X] No
```

DIV-6764: Adding resp-solicitor CRUD permissions

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-prod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json

Feature-toggling existing event.

DIV-6767: Feature-toggling the solicitorSubmitAOS event for the resp-solicitor

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-resp-journey-nonprod.json

I've missed a few fields on my previous PR. Sorry.
```
[ ] Yes
[ ] No
```

DIV-6764: Authorising fields for resp-solicitor

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-resp-journey-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6764
Adding appropriate CRUD permissions to event to fix "No field found" error.
```
[ ] Yes
[x] No
```

DIV-6764: Fixing no field found issue

---

definitions/divorce/json/CaseTypeTab/CaseTypeTab.json

DIV-6767: Adding missing fields to AOS tab

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-resp-journey-nonprod.json
definitions/divorce/json/CaseField/CaseField-resp-journey-nonprod.json

One of the labels was declared as text.
```
[ ] Yes
[ ] No
```

DIV-6764: Making event work with minimal permission

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-prod.json
definitions/divorce/json/CaseEvent/CaseEvent.json
test/unit/definitions/divorce/UserRoleStateAuth.test.js
test/unit/utils/utils.js

https://tools.hmcts.net/jira/browse/DIV-6777
The pre-states of some existing events have been extended to also include `AosDrafted` so that the events that are triggered by the `AosOverdueJob` can handle cases in this state as well.
```
[ ] Yes
[x] No
```

DIV-6777: Extend AOS overdue job to pick-up cases from state AosDrafted

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-resp-journey-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-prod.json
definitions/divorce/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/DIV-6780
Extending events so the Alternative service journey takes into account the new state 'AOSdrafted'.
```
[ ] Yes
[x] No
```

DIV-6780: Extending events for AosDrafted

---

definitions/divorce/json/FixedLists/FixedLists.json

reintroduce cheque payment type to fixed list

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json

RPET-873:give sol more permission to action draft decree nisi

---

package.json

https://tools.hmcts.net/jira/browse/DIV-6630
URL inversion for DIV-6630
```
[ ] Yes
[ ] No
```

DIV-6630: Judge cost order event page - aat url Inversion

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/CaseEvent/CaseEvent.json

This commit was accidentally pushed to master. I've fixed the repo rules that allowed this to happen.
```
[ ] Yes
[X] No
```

Revert "div6853-superUser"

---

definitions/divorce/json/CaseEvent/CaseEvent.json

Adding missing callbacks.
```
[ ] Yes
[X] No
```

RPET-891: Adding missing callbacks

---

definitions/divorce/json/CaseEvent/CaseEvent.json

We must follow the process. It will get back to master as soon as we can.
Reverts hmcts/div-ccd-definitions#776

Revert "RPET-891: Adding missing callbacks"

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-bailiff-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-bailiff-nonprod.json
definitions/divorce/json/CaseField/CaseField-bailiff-nonprod.json

https://tools.hmcts.net/jira/browse/DIV-6089
Displaying label when continuing because of served by bailiff successful
```
[ ] Yes
[x] No
```

DIV-6089: Displaying label when served by bailiff successful

---

definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField-resp-journey-nonprod.json
definitions/divorce/json/CaseField/CaseField-resp-journey-nonprod.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab-resp-journey-nonprod.json
definitions/divorce/json/CaseTypeTab/CaseTypeTab.json
package.json

https://tools.hmcts.net/jira/browse/DIV-6807
Add notice of proceedings details to AOS tab
```
[ ] Yes
[ ] No
```

DIV-6807: Add notice of proceedings details to AOS tab

---

definitions/divorce/json/CaseEvent/CaseEvent-share-a-case-nonprod.json
package.json

https://tools.hmcts.net/jira/browse/DIV-6844
- Remove /allow-share-a-case call from case submission event
```
[ ] Yes
[ ] No
```

DIV-6844: Merge allow share case with about to start callback

---

definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-resp-journey-prod.json
definitions/divorce/json/CaseEvent/CaseEvent.json

Pointing 'issueAOS' to the new endpoint in non-prod
```
[ ] Yes
[X] No
```

DIV-6762: Pointing 'issueAOS' to the new endpoint in non-prod

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState-share-a-case-nonprod.json

Adding needed permission for "Case submission" event.
```
[ ] Yes
[ ] No
```

DIV-6844: Adding authorisation for CAA user

---

definitions/divorce/json/CaseEvent/CaseEvent-bailiff-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-bailiff-prod.json

https://tools.hmcts.net/jira/browse/DIV-6871

DIV-6871: event 'solicitorDraftAOS' gets state 'AosOverdue' added to pre-states

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields.json

https://tools.hmcts.net/jira/browse/DIV-6878
Makes additional comments on AOS statement of truth `OPTIONAL`
```
[ ] Yes
[x] No
```

DIV-6878: Make additional comments optional

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
definitions/divorce/json/AuthorisationCaseField/AuthorisationCaseField.json
definitions/divorce/json/CaseEvent/CaseEvent.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields.json

[Corresponding div-cos PR](https://github.com/hmcts/div-case-orchestration-service/pull/1320)
- RPET-599 Change Service Method (https://github.com/hmcts/div-ccd-definitions/pull/703)
- RPET-567 update solConfirmPersonalService callback endpoint (https://github.com/hmcts/div-ccd-definitions/pull/722)
- RPET-269 no ccd config changes required
[RPET-269](https://tools.hmcts.net/jira/browse/RPET-269)
[RPET-567](https://tools.hmcts.net/jira/browse/RPET-567)
[RPET-559](https://tools.hmcts.net/jira/browse/RPET-559)
Combined release PR for RPET-269, RPET-567, and RPET-559

RELEASE RPET-269, RPET-567, RPET-559

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/CaseEvent/CaseEvent-nonprod.json
definitions/divorce/json/CaseEventToFields/CaseEventToFields-nonprod.json

New test event to add required data to make case eligible for DA and grant DA.
```
[ ] Yes
[x] No
```

New test event: Add data required for DA

---

README.md
charts/div-ccd-definitions/Chart.yaml

Fix Preview document upload

---

definitions/divorce/json/AuthorisationCaseState/AuthorisationCaseState.json

Story:
https://tools.hmcts.net/jira/browse/RPET-979

RPET-979: remove caa permissions

---

definitions/divorce/json/CaseEvent/CaseEvent.json

https://tools.hmcts.net/jira/browse/RPET-961
Adding callback to reissueFromServiceAppRejected
```
[ ] Yes
[x] No
```

RPET 961 Adding callback to reissueFromServiceAppRejected

---

test/functional/admin_test.js

DFR-649: Fix config deployment in test

---

Jenkinsfile_CNP
test/functional/admin_test.js

Dfr 649 fix spreadsheet deployment

---

charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/values.preview.template.yaml
charts/div-ccd-definitions/values.yaml

Dfr 649 add div emca to charts

---

definitions/divorce/json/CaseField/CaseField.json
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DFR-627
copy of https://github.com/hmcts/div-ccd-definitions/pull/912

Dfr 627 update solicitor address field 2

---

package.json
yarn.lock

DFR-833: Upgrade puppeteer

---

charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/values.preview.template.yaml
charts/div-ccd-definitions/values.yaml
definitions/divorce/json/CaseField/CaseField.json
package.json
yarn.lock

DFR-613 Preview env for test

---

package.json
yarn.lock

DFR-854
Upgrade properties-volume for div-ccd-defintions
```
[ ] Yes
[x] No
```

DFR-854: Upgrade properties-volume for div-ccd-defintions

---

definitions/divorce/json/CaseEventToFields/CaseEventToFields.json

Update FieldShowCondition for D8DivorceCostsClaim and D8FinancialOrder fields

DFR-919 Update CaseEventToFields.json

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-prod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
package.json

Dfr 994 enable solicitor create case

---

charts/div-ccd-definitions/Chart.yaml
charts/div-ccd-definitions/values.preview.template.yaml

Bump chart version to 8.0.17

---

definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent-nonprod.json
definitions/divorce/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json

https://tools.hmcts.net/jira/browse/DFR-1306
remove create authorisation for citizen on create event
```
[ ] Yes
[x] No
```

DFR-1306 - remove create authorisation for citizen on create event

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DFR-1630

bump qs and express

---

charts/div-ccd-definitions/Chart.yaml

https://tools.hmcts.net/jira/browse/DFR-1630

DFR-1630: update frontend chart versions

---

charts/div-ccd-definitions/Chart.yaml

https://tools.hmcts.net/jira/browse/DFR-1492

DFR-1492 bump nodejs version

---

charts/div-ccd-definitions/Chart.yaml

https://tools.hmcts.net/jira/browse/DFR-1492

Dfr 1492 divorce patching

---

.github/CODEOWNERS
.github/renovate.json
charts/div-ccd-definitions/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/DTSPO-12024
Configure renovate to update helm chart dependencies
Add codeowners
Remove traefik annotation causing error in pipeline
```
[ ] Yes
[x] No
```

DTSPO-12024 - Configure renovate
